---
- name: "Python | Install"
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present
  become: true

# - name: "Python | Install pip packages"
#   ansible.builtin.pip:
#     name: "{{ item }}"
#     state: present
#   loop:
#     - shell-gpt==0.9.0
