---
- name: "Keyboard | Ensure required packages are installed"
  apt:
    name:
      - git
      - build-essential
    state: present
  become: true

- name: "Keyboard | Clone the keyd repository"
  git:
    repo: "https://github.com/rvaiya/keyd"
    dest: "/tmp/keyd"
    version: "master"

- name: "Keyboard | Build keyd"
  become: true
  make:
    chdir: "/tmp/keyd"

- name: "Keyboard | Install keyd"
  become: true
  make:
    chdir: "/tmp/keyd"
    target: install

- name: "Keyboard | Deploy keyd configuration"
  copy:
    src: "keyd.conf"
    dest: "/etc/keyd/default.conf"
    mode: "0644"

- name: "Keyboard | Enable and start keyd service"
  systemd:
    name: keyd
    enabled: true
    state: started

- name: Keyboard | Copy custom keyboard layout
  ansible.builtin.copy:
    src: custom
    dest: /usr/share/X11/xkb/symbols/custom
    owner: root
    group: root
    mode: '0644'
  notify: Reload X11 keyboard configuration
  become: yes

- name: Keyboard | Configure the custom layout as the default
  ansible.builtin.template:
    src: keyboard.conf.j2
    dest: /etc/X11/xorg.conf.d/00-keyboard.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload X11 keyboard configuration
  become: yes

- name: Keyboard | Set the custom layout system-wide (for init systems)
  ansible.builtin.lineinfile:
    path: /etc/default/keyboard
    regexp: '^XKBLAYOUT='
    line: 'XKBLAYOUT="custom"'
    create: yes
  notify: Reload X11 keyboard configuration
  become: yes
