---
- name: "Keyboard | Ensure required packages are installed"
  apt:
    name:
      - git
      - build-essential
    state: present
  become: true

- name: "Keyboard | Clone the keyd repository"
  git:
    repo: "https://github.com/rvaiya/keyd"
    dest: "/tmp/keyd"
    version: "master"

- name: "Keyboard | Build keyd"
  become: true
  make:
    chdir: "/tmp/keyd"

- name: "Keyboard | Install keyd"
  become: true
  make:
    chdir: "/tmp/keyd"
    target: install

- name: "Keyboard | Deploy keyd configuration"
  become: true
  copy:
    src: "keyd.conf"
    dest: "/etc/keyd/default.conf"
    mode: "0644"

- name: "Keyboard | Enable and start keyd service"
  become: true
  systemd:
    name: keyd
    enabled: true
    state: started

- name: Keyboard | Copy custom keyboard layout
  ansible.builtin.copy:
    src: custom
    dest: /usr/share/X11/xkb/symbols/custom
    owner: root
    group: root
    mode: "0644"
  notify: Reload X11 keyboard configuration
  become: yes

- name: Keyboard | Install required packages for dconf
  apt:
    name:
      - python3-psutil
      - dconf-cli
      - dbus-x11
      - gnome-shell
    state: present
  become: true

- name: Check if GNOME is installed
  command: gnome-shell --version
  register: gnome_version
  ignore_errors: yes

- name: Check for dconf
  command: which dconf
  register: dconf_path
  ignore_errors: yes

- name: Check for python3-psutil
  package:
    name: python3-psutil
    state: present
  check_mode: yes
  register: psutil_check

- name: Display results
  debug:
    msg:
      - "GNOME installed: {{ gnome_version.rc == 0 }}"
      - "dconf available: {{ dconf_path.rc == 0 }}"
      - "python3-psutil installed: {{ not psutil_check.changed }}"

- name: Read currently available keyboard layouts in Gnome
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    state: read
  register: keyboard_layouts

- name: Keyboard | Set custom keyboard layout as default
  community.general.dconf:
    key: /org/gnome/desktop/input-sources/sources
    value: "[('xkb', 'custom')]"
    state: present

# - name: Reload keyd configuration
#   ansible.builtin.command:
#     cmd: "keyd reload"

# - name: Set custom layout with setxkbmap
#   ansible.builtin.command:
#     cmd: "setxkbmap custom"

- name: Keyboard | Configure the custom layout as the default
  ansible.builtin.template:
    src: keyboard.conf.j2
    dest: /etc/X11/xorg.conf.d/00-keyboard.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload X11 keyboard configuration
  become: yes

- name: Keyboard | Set the custom layout system-wide (for init systems)
  ansible.builtin.lineinfile:
    path: /etc/default/keyboard
    regexp: "^XKBLAYOUT="
    line: 'XKBLAYOUT="custom"'
    create: yes
  notify: Reload X11 keyboard configuration
  become: yes

- name: "Keyboard | Enable and start keyd service"
  become: true
  systemd:
    name: keyd
    enabled: true
    state: restarted
