---
- name: "Keyboard | Ensure required packages are installed"
  apt:
    name:
      - git
      - build-essential
    state: present
  become: true

- name: "Keyboard | Clone the keyd repository"
  git:
    repo: "https://github.com/rvaiya/keyd"
    dest: "/tmp/keyd"
    version: "master"

- name: "Keyboard | Build keyd"
  become: true
  make:
    chdir: "/tmp/keyd"

- name: "Keyboard | Install keyd"
  become: true
  make:
    chdir: "/tmp/keyd"
    target: install

- name: "Keyboard | Deploy keyd configuration"
  become: true
  copy:
    src: "keyd.conf"
    dest: "/etc/keyd/default.conf"
    mode: "0644"

- name: "Keyboard | Enable and start keyd service"
  become: true
  systemd:
    name: keyd
    enabled: true
    state: started

- name: Keyboard | Copy custom keyboard layout
  ansible.builtin.copy:
    src: custom
    dest: /usr/share/X11/xkb/symbols/custom
    owner: root
    group: root
    mode: '0644'
  notify: Reload X11 keyboard configuration
  become: yes

- name: Read currently available keyboard layouts in Gnome
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    state: read
  register: keyboard_layouts

- name: Keyboard | Set custom keyboard layout as default
  become: yes
  community.general.dconf:
    key: /org/gnome/desktop/input-sources/sources
    value: "[('xkb', 'custom')]"
    state: present

# - name: Reload keyd configuration
#   ansible.builtin.command:
#     cmd: "keyd reload"

# - name: Set custom layout with setxkbmap
#   ansible.builtin.command:
#     cmd: "setxkbmap custom"

# - name: Keyboard | Configure the custom layout as the default
#   ansible.builtin.template:
#     src: keyboard.conf.j2
#     dest: /etc/X11/xorg.conf.d/00-keyboard.conf
#     owner: root
#     group: root
#     mode: '0644'
#   notify: Reload X11 keyboard configuration
#   become: yes

# - name: Keyboard | Set the custom layout system-wide (for init systems)
#   ansible.builtin.lineinfile:
#     path: /etc/default/keyboard
#     regexp: '^XKBLAYOUT='
#     line: 'XKBLAYOUT="custom"'
#     create: yes
#   notify: Reload X11 keyboard configuration
#   become: yes
